### ISSUE TITLE
Gallery Styling fixes

### ISSUE THREAD

**Issue by d1scrd** [COS301-SE-2024/Autonomous-Car-Vision#84]
- The dynamic resizing should be removed.
- The gallery item cards need a styling revamp. 
- Remove Gallery heading at top of page.
- Download revamp. (should be component on its own)
- File name.
- Search / filter.
- Involves updates to local registry.
- Basically an entire styling revamp.

**Comment by JordanTimberlake** [comment]
## Want to add some more changes

- User can click between card view or list view - Similar to the file explorer on windows.
- Maybe can add more sorting options such that user can sort according to the name, date added, processed or not.
- Will need to add more information to gallery card to add the date added.
